USE [master]
GO

/****** Object:  Database [Strikethrough_Dev]    Script Date: 4/28/2013 12:12:35 AM ******/
CREATE DATABASE [Strikethrough_Dev] ON  PRIMARY 
( NAME = N'Strikethrough_Dev', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Strikethrough_Dev.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Strikethrough_Dev_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Strikethrough_Dev_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Strikethrough_Dev] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Strikethrough_Dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Strikethrough_Dev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET ARITHABORT OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Strikethrough_Dev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Strikethrough_Dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Strikethrough_Dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Strikethrough_Dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Strikethrough_Dev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET RECOVERY FULL 
GO

ALTER DATABASE [Strikethrough_Dev] SET  MULTI_USER 
GO

ALTER DATABASE [Strikethrough_Dev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Strikethrough_Dev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Strikethrough_Dev] SET  READ_WRITE 
GO

